In [1]:
import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt

In [2]:
# hadamard multiplication is: Element-Wise multiplication
# only valid for two vectors with same number of elements
v1 = [1, 2, 3]
v2 = [3, 4, 5]
v3 = np.multiply(v1,v2)
print(v3)

[ 3  8 15]


In [3]:
# outer product w/ vectors

op = np.outer(v1, v2)
print(op)

[[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]


In [4]:
# cross product w/ vectors
# defined only for two 3d vectors
# result is a 3d vector

cp = np.cross(v1, v2)
print(cp)

[-2  4 -2]


In [ ]:
# complex #
z = np.complex(3,4)

# magnitude
print(np.linalg.norm(z))

# transpose
print(np.transpose(z)*z)

# hermitian transpose
print(np.transpose(z.conjugate())*z)

# complex vector
v = np.array([3,4j,5+2j,2-5j])
print(v.T)
print(np.transpose(v))
print(np.transpose(v.conjugate()))

 